### ISSUE TITLE
Issue on client side

### ISSUE THREAD

**Issue by quintendc** [auth0-blog/blazor-interactive-auto#2]
I followed the tutorial, and it looks like their is still an issue once i switch to the client side (counter) i can see my username and 1 second later it disappears.

Once i switch to counter page it calls the `OnInitializedAsync` method i see the username, then ~1 second later it calls again the `OnInitializedAsync` method and the username is empty.

When i check the authenticationstate on the second call the user is not authenticated anymore.

**Comment by andychiare** [comment]
Are you getting the same issue by downloading and running this project?

The behavior you describe makes me think of two cases:

- The authentication state sync is not correctly implemented, i.e., the authentication state is not correctly deserialized in the client. Please, double check the `PersistentAuthenticationStateProvider` implementation.
- The authentication state is not propagated in the component hierarchy. Make sure you added `builder.Services.AddCascadingAuthenticationState();` to the client's `Program.cs` file.

Otherwise, if you can share some code, I can take a look.

**Comment by quintendc** [comment]
Hello,

I have zipped my project so you can take a look their is nothing extra added only an extra page and i removed the domain & clientId from the appsettings.json

[secondbrain.zip](https://github.com/auth0-blog/blazor-interactive-auto/files/14074064/secondbrain.zip)


PersistentAuthenticationStateProvider.cs located in client application

```
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Authorization;
using SecondBrain.Blazor.Client.AuthenticationStateSyncer;
using System.Security.Claims;

public class PersistentAuthenticationStateProvider(PersistentComponentState persistentState) : AuthenticationStateProvider
{
    private static readonly Task<AuthenticationState> _unauthenticatedTask =
        Task.FromResult(new AuthenticationState(new ClaimsPrincipal(new ClaimsIdentity())));

    public override Task<AuthenticationState> GetAuthenticationStateAsync()
    {
        if (!persistentState.TryTakeFromJson<UserInfo>(nameof(UserInfo), out var userInfo) || userInfo is null)
        {
            return _unauthenticatedTask;
        }

        Claim[] claims = [
            new Claim(ClaimTypes.NameIdentifier, userInfo.UserId),
            new Claim(ClaimTypes.Name, userInfo.Name),
            new Claim(ClaimTypes.Email, userInfo.Email)];

        return Task.FromResult(
            new AuthenticationState(new ClaimsPrincipal(new ClaimsIdentity(claims,
                authenticationType: nameof(PersistentAuthenticationStateProvider)))));
    }
}
```

and `builder.Services.AddCascadingAuthenticationState();` is added in the program.cs of the client application.

thanks in advance,

**Comment by grantcolley** [comment]
@quintendc, @andychiare 

> ...the client side (counter) i can see my username and 1 second later it disappears.

I had the same issue copying the steps in the tutorial, but ***not*** when I downloaded the source from github.

I noticed two differences comparing the tutorial code and the source code in github, and made the following changes to get it working:

First, in `PersistingRevalidatingAuthenticationStateProvider.OnPersistingAsync()` in the server project, persist `UserInfo` state when the value of the `name` Claim is not null, rather than `email` (which in my case is null).
```C#
        private async Task OnPersistingAsync()
        {
                // ...code removed for brevity...

                if (userId != null && name != null)  // 👈 null check on name, rather than email
                {
                    _state.PersistAsJson(nameof(UserInfo), new UserInfo
                    {
                        UserId = userId,
                        Name = name,
                        Email = email
                    });
                }

                // ...code removed for brevity...
        }
```

Second, in `PersistentAuthenticationStateProvider.GetAuthenticationStateAsync()` in the client project, add null checks when creating a `Claim`, in particular for `userInfo.Email` (which in my case was null and threw an exception).
```C#
        public override Task<AuthenticationState> GetAuthenticationStateAsync()
        {
                // ...code removed for brevity...
      
                Claim[] claims = [
                    new Claim(ClaimTypes.NameIdentifier, userInfo.UserId),
                    new Claim(ClaimTypes.Name, userInfo.Name ?? string.Empty),
                    new Claim(ClaimTypes.Email, userInfo.Email ?? string.Empty)];  // 👈 null check on Email
            
                // ...code removed for brevity...
        }
```

**Comment by quintendc** [comment]
Hello @grantcolley,

I changed my code with your code and it is working.

Thank you

**Comment by andychiare** [comment]
Hey @grantcolley, thank you very much for reporting this fix. Actually, I had this typo in my initial code and then fixed it, but forgot to fix the code snippets in the article.
